/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardRepositoriosRouteImport } from './routes/dashboard/repositorios'
import { Route as DashboardPrimerosPasosRouteImport } from './routes/dashboard/primeros-pasos'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiGithubReposRouteImport } from './routes/api.github.repos'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRepositoriosRoute = DashboardRepositoriosRouteImport.update({
  id: '/repositorios',
  path: '/repositorios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrimerosPasosRoute = DashboardPrimerosPasosRouteImport.update({
  id: '/primeros-pasos',
  path: '/primeros-pasos',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/primeros-pasos': typeof DashboardPrimerosPasosRoute
  '/dashboard/repositorios': typeof DashboardRepositoriosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/github/repos': typeof ApiGithubReposRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/primeros-pasos': typeof DashboardPrimerosPasosRoute
  '/dashboard/repositorios': typeof DashboardRepositoriosRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/github/repos': typeof ApiGithubReposRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/primeros-pasos': typeof DashboardPrimerosPasosRoute
  '/dashboard/repositorios': typeof DashboardRepositoriosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/github/repos': typeof ApiGithubReposRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/primeros-pasos'
    | '/dashboard/repositorios'
    | '/dashboard/'
    | '/api/github/repos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/dashboard/primeros-pasos'
    | '/dashboard/repositorios'
    | '/dashboard'
    | '/api/github/repos'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/primeros-pasos'
    | '/dashboard/repositorios'
    | '/dashboard/'
    | '/api/github/repos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/repositorios': {
      id: '/dashboard/repositorios'
      path: '/repositorios'
      fullPath: '/dashboard/repositorios'
      preLoaderRoute: typeof DashboardRepositoriosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/primeros-pasos': {
      id: '/dashboard/primeros-pasos'
      path: '/primeros-pasos'
      fullPath: '/dashboard/primeros-pasos'
      preLoaderRoute: typeof DashboardPrimerosPasosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardPrimerosPasosRoute: typeof DashboardPrimerosPasosRoute
  DashboardRepositoriosRoute: typeof DashboardRepositoriosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPrimerosPasosRoute: DashboardPrimerosPasosRoute,
  DashboardRepositoriosRoute: DashboardRepositoriosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
